# Generated by Django 4.1.2 on 2022-10-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_category_alter_news_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='quotation',
            field=models.TextField(blank=True, null=True, verbose_name='Короткая цитата новости'),
        ),
    ]
