# Generated by Django 4.1.2 on 2022-11-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемое?'),
        ),
    ]
