# Generated by Django 4.1.2 on 2022-11-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='В рекомендуемое?'),
        ),
    ]
