# Generated by Django 4.1.2 on 2022-12-06 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_groupcategory_groupstrips'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkiCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ski_name', models.CharField(db_index=True, max_length=120, verbose_name='Название ГЛЦ')),
                ('ski_info', models.TextField(max_length=5000, verbose_name='Информация о ГЛЦ')),
                ('ski_logo', models.ImageField(upload_to='ski_logo/', verbose_name='Лого ГЛЦ')),
                ('ski_img_one', models.ImageField(upload_to='ski_img/', verbose_name='Фото ГЛЦ 1')),
                ('ski_img_two', models.ImageField(upload_to='ski_img/', verbose_name='Фото ГЛЦ 2')),
                ('ski_img_three', models.ImageField(upload_to='ski_img/', verbose_name='Фото ГЛЦ 3')),
                ('ski_link', models.URLField(verbose_name='Ссылка на ГЛЦ')),
            ],
            options={
                'verbose_name': 'Наименование места поездки',
                'ordering': ['ski_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='groupstrips',
            options={'ordering': ['trip_title'], 'verbose_name': 'Выезды с группой', 'verbose_name_plural': 'Выезды с группой'},
        ),
        migrations.RenameField(
            model_name='groupstrips',
            old_name='date_trip',
            new_name='trip_date',
        ),
        migrations.RenameField(
            model_name='groupstrips',
            old_name='info_trip',
            new_name='trip_info',
        ),
        migrations.RenameField(
            model_name='groupstrips',
            old_name='link_trip',
            new_name='trip_link',
        ),
        migrations.RenameField(
            model_name='groupstrips',
            old_name='logo_trip',
            new_name='trip_logo',
        ),
        migrations.RenameField(
            model_name='groupstrips',
            old_name='price_trip',
            new_name='trip_price',
        ),
        migrations.RenameField(
            model_name='groupstrips',
            old_name='title_trip',
            new_name='trip_title',
        ),
        migrations.RemoveField(
            model_name='groupstrips',
            name='group_category',
        ),
        migrations.DeleteModel(
            name='GroupCategory',
        ),
        migrations.AddField(
            model_name='groupstrips',
            name='trip_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.skicenters', verbose_name='Место поездки (выбор ГЛЦ)'),
        ),
    ]
