# Generated by Django 4.1.2 on 2022-12-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_skicenters_alter_groupstrips_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skicenters',
            name='ski_logo',
        ),
    ]
