# Generated by Django 4.1.2 on 2022-12-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_remove_skicenters_ski_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_title', models.CharField(max_length=150, verbose_name='Название группы')),
                ('trip_logo', models.ImageField(upload_to='group_logo/', verbose_name='Лого группы')),
                ('trip_info', models.TextField(max_length=5000, verbose_name='Информация о группе')),
                ('trip_link', models.URLField(verbose_name='Ссылка на группу')),
            ],
            options={
                'verbose_name': 'Выезды с группой',
                'verbose_name_plural': 'Выезды с группой',
                'ordering': ['trip_title'],
            },
        ),
        migrations.AlterModelOptions(
            name='groupstrips',
            options={},
        ),
        migrations.RemoveField(
            model_name='groupstrips',
            name='trip_info',
        ),
        migrations.RemoveField(
            model_name='groupstrips',
            name='trip_link',
        ),
        migrations.RemoveField(
            model_name='groupstrips',
            name='trip_logo',
        ),
        migrations.RemoveField(
            model_name='groupstrips',
            name='trip_title',
        ),
        migrations.AddField(
            model_name='groupstrips',
            name='trip_name_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.groups', verbose_name='Кто едет'),
        ),
    ]
