# Generated by Django 4.1.2 on 2022-12-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_groups_alter_groupstrips_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstrips',
            name='trip_date',
            field=models.DateField(verbose_name='Дата начала поездки'),
        ),
    ]
