# Generated by Django 4.1.2 on 2022-12-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_groupstrips_trip_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupstrips',
            old_name='trip_date',
            new_name='trip_date_start',
        ),
    ]
