# Generated by Django 4.1.2 on 2022-12-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_rename_trip_date_groupstrips_trip_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstrips',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupstrips',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
