# Generated by Django 4.1.2 on 2022-12-08 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_groupstrips_date_end_groupstrips_date_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['trip_title'], 'verbose_name': 'ГЛЦ - Группы', 'verbose_name_plural': 'ГЛЦ - Группы'},
        ),
        migrations.AlterModelOptions(
            name='groupstrips',
            options={'verbose_name': 'ГЛЦ - Расписание поездок', 'verbose_name_plural': 'ГЛЦ - Расписание поездок'},
        ),
        migrations.AlterModelOptions(
            name='skicenters',
            options={'ordering': ['ski_name'], 'verbose_name': 'ГЛЦ - инфа', 'verbose_name_plural': 'ГЛЦ - инфа'},
        ),
        migrations.RemoveField(
            model_name='groupstrips',
            name='trip_date_start',
        ),
        migrations.RemoveField(
            model_name='skicenters',
            name='ski_img_three',
        ),
        migrations.AddField(
            model_name='groupstrips',
            name='trip_text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Дополнительная инфа по поездке'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='trip_title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='groupstrips',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания поездки'),
        ),
        migrations.AlterField(
            model_name='groupstrips',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала поездки'),
        ),
        migrations.AlterField(
            model_name='groupstrips',
            name='trip_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='glc', to='news.skicenters', verbose_name='Место поездки (выбор ГЛЦ)'),
        ),
    ]
