# Generated by Django 4.1.2 on 2022-12-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_groupstrips_date_end_groupstrips_date_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['trip_title'], 'verbose_name': 'Группы', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='groupstrips',
            options={'verbose_name': 'Расписание поездок', 'verbose_name_plural': 'Расписание поездок'},
        ),
        migrations.AlterModelOptions(
            name='skicenters',
            options={'ordering': ['ski_name'], 'verbose_name': 'Название ГЛЦ для поездок', 'verbose_name_plural': 'Название ГЛЦ для поездок'},
        ),
        migrations.RemoveField(
            model_name='groupstrips',
            name='trip_date_start',
        ),
        migrations.AddField(
            model_name='groupstrips',
            name='trip_text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Дополнительная инфа по поездке'),
        ),
        migrations.AlterField(
            model_name='groupstrips',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания поездки'),
        ),
        migrations.AlterField(
            model_name='groupstrips',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала поездки'),
        ),
    ]
