# Generated by Django 4.1.2 on 2022-12-08 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_groups_options_alter_groupstrips_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstrips',
            name='trip_name_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='news.groups', verbose_name='Кто едет'),
        ),
    ]
